MODEL:
  TYPE: focal
  NAME: focal_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.2
  FOCAL:
    EMBED_DIM: 64
    # DEPTHS: [1, 2, 21, 2]
    DEPTHS: [3, 3, 16, 3]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7 
    FOCAL_POOL: "fc"
    FOCAL_STAGES: [0, 1, 2, 3]
    FOCAL_LEVELS: [2, 2, 2, 2]
    FOCAL_WINDOWS: [7, 5, 3, 1]
    EXPAND_SIZES: [3, 3, 3, 3]