MODEL:
  TYPE: focal
  NAME: focal_large_patch4_window7_224
  DROP_PATH_RATE: 0.5
  FOCAL:
    EMBED_DIM: [192]
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 6, 12, 24, 48 ]
    WINDOW_SIZE: 7 
    FOCAL_POOL: "conv"