DATA:
  IMG_SIZE: 384
MODEL:
  TYPE: swin
  NAME: swin_large_patch4_window7_224
  DROP_PATH_RATE: 0.5
  FOCAL:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12  